W4D5/music_app_w_specs/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :bands

end

W4D5/music_app_w_specs/app/models/band.rb
# == Schema Information
#
# Table name: bands
#
#  id         :bigint(8)        not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Band < ApplicationRecord
  validates :name, presence: true
end

W4D5/music_app_w_specs/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint(8)        not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ApplicationRecord
  validates :email, :session_token, :password_digest, presence: true, uniqueness: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token
  attr_reader :password

  def self.generate_session_token
    SecureRandom.urlsafe_base64
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
    self.session_token
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

  def password=(pw)
    @password = pw
    self.password_digest = BCrypt::Password.create(pw)
  end

  def is_password?(pw)
    BCrypt::Password.new(self.password_digest).is_password?(pw)
  end

  def self.find_by_credentials(email, pw)
    user = User.find_by(email: email)
    user && user.is_password?(pw) ? user : nil
  end
end

W4D5/music_app_w_specs/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def login!(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
    @current_user = nil
  end

  def logged_in?
    !!current_user
  end

  def require_login
    redirect_to new_session_url unless logged_in?
  end

  def require_logout
    redirect_to users_url if logged_in?
  end
end

W4D5/music_app_w_specs/app/controllers/bands_controller.rb
class BandsController < ApplicationController
  # before_action :require_login

  def index
    @bands = Band.all
    render :index
  end

  def show
    @band = Band.find(params[:id])
    render :show
  end

  private

  def band_params
    params.require(:band).permit(:name)
  end
end

W4D5/music_app_w_specs/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_login, only: [:destroy]
  before_action :require_logout, only: [:new, :create]

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.find_by_credentials(params[:user][:email], params[:user][:password])
    if @user
      login!(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = ['Wrong! Try again.']
      redirect_to new_session_url
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

W4D5/music_app_w_specs/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_url(@user.id)

    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

    def show
      @user = User.find(params[:id])
      render :show
    end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

W4D5/music_app_w_specs/app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    "<input type='hidden' name='authenticity_token' value='<%= form_authenticity_token %>'/>".html_safe
  end

  def patch_method_overide
    "<input type='hidden' name='_method' value='patch'>".html_safe
  end

  def get_method_overide
    "<input type='hidden' name='_method' value='get'>".html_safe
  end

  def delete_method_overide
    "<input type='hidden' name='_method' value='delete'>".html_safe
  end


end

W4D5/music_app_w_specs/app/views/bands/index.html.erb
<h1>All the bands</h1>
<% @bands.each do |band| %>
Band: <%= band.name %><br>
<% end %>

W4D5/music_app_w_specs/app/views/bands/show.html.erb
<h1>Here's your band!</h1>

W4D5/music_app_w_specs/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>My Space 2.0</h1>
      <% if logged_in? %>
      <h2>Logged In As : <%= current_user.email %></h2>
      <form action="<%= session_url %>" method="post">
        <%= auth_token %>
        <%= delete_method_overide %>
        <input class="header_button" type="submit" name="" value="Logout!">
      </form>
      <form action="<%= bands_url %>" method="post">
        <%= auth_token %>
        <%= get_method_overide %>
        <input class="header_button" type="submit" name="" value="See all bands!">
      </form>
      <% else %>
        <form action="<%= new_session_url %>" method="post">
          <%= get_method_overide %>
          <input class="header_button" type="submit" name="" value="Login!">
        </form>

        <form action="<%= new_user_url %>" method="post">
          <%= get_method_overide %>
          <input class="header_button" type="submit" name="" value="Sign Up!">
        </form>
      <% end %>
    </header>
    <%= yield %>
    <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
    <%= error %><br>
    <% end %>
    <% end %>
  </body>
</html>

W4D5/music_app_w_specs/app/views/users/_form.html.erb
<% if type == :new
  action_url = users_url
  button_val = "Create yourself!"
elsif type == :login
  action_url = session_url
  button_val = "Login, yo!"
end %>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>

  <label for="email">Email:</label>
  <input type="text" id="email" name="user[email]" value="<%= user.email %>">

  <label for="password">Password:</label>
  <input type="password" id="password" name="user[password]" value="<%= user.password %>">
  <input type="submit" value="<%= button_val %>">
</form>

W4D5/music_app_w_specs/app/views/users/new.html.erb
<h1>Sign Up Page</h1>

<%= render "form", user: @user, type: :new %>

W4D5/music_app_w_specs/app/views/users/show.html.erb
<h1>Here's your profile:</h1>

<%= @user.email %>